repos:
  - repo: local
    hooks:
      - id: ruff lint
        name: Run linter
        entry: ruff format
        language: system
        types: [python]
      - id: ruff fix
        name: Run ruff static analysis
        entry: ruff check --fix
        language: system
        types: [python]

